## A Numpy Primer

`Numpy` is a `Python` package for scientific computing. It supports N-dimensional arrays and has many linear algebra functions built in.  

In [3]:
#To use numpy, you first need to import the package. You can do it in two ways:
import numpy
#or
import numpy as np
#The second solution is in general preferable so that we know from which package each function is coming from. 
#You will have to write np.<your_function> to make it works.

Let's create two numpy arrays from lists of numbers:

In [4]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [5]:
b = np.array([3,5,1])
b

array([3, 5, 1])

Some of the common arithmetic functions cannot be performed on lists, but numpy arrays. For example, if we want to mulitply every element of a list by 2:

In [6]:
[2,3,4]*2

[2, 3, 4, 2, 3, 4]

This is not what we expected. But if we do this on the numpy array `a`:

In [7]:
a*2

array([4, 6, 8])

That looks good!

There are many math functions on the numpy arrays. For example, calculating a dot product between two arrays:

In [8]:
np.dot(a,b)

25

In [9]:
# alternatively
a.dot(b)

25

We can intialize an array with all zeros:

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Or a range using the `arange` function:

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

2D arrays can also be created similarly, with two number inputs as dimentions. Here we create a 2 by 3 matrix of random numbers:

In [12]:
np.random.seed(2)
randmat = np.random.rand(2,3)
randmat

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

We can take a look at some information about the array:

In [13]:
print(randmat.shape)
print(randmat.size)
print(randmat.dtype)

(2, 3)
6
float64


Indexing and slicing are very similar to lists:

In [14]:
randmat[0,2]

0.5496624778787091

In [15]:
randmat[:,2]

array([0.54966248, 0.33033482])

In [16]:
randmat[0,:2]

array([0.4359949 , 0.02592623])

Now we can build `pandas` dataframes from a dictionary of numpy arrays: 

In [17]:
import pandas as pd
dict = {'first': np.random.rand(4),
        'second':np.random.rand(4)}
df = pd.DataFrame(dict)
df

first    second
0  0.204649  0.621134
1  0.619271  0.529142
2  0.299655  0.134580
3  0.266827  0.513578